/**
 * Check the variable for living in an object wrapper
 * These can be generated by new String / Number etc.
 * see https://developer.mozilla.org/en-US/docs/Glossary/Primitive
 * @param {any} value - any value to check
 * @returns {boolean} is a wrapped primitive
 */
const isWrappedPrimitive = (value) =>
    typeof value === 'object' &&
    (value instanceof String ||
        value instanceof Number ||
        //        value instanceof BigInt ||
        value instanceof Boolean ||
        value instanceof Symbol)

export { isWrappedPrimitive }
